// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SchedularService.proto

package SchedularService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RowType int32

const (
	RowType_Editorial      RowType = 0
	RowType_Recommendation RowType = 1
	RowType_Dynamic        RowType = 2
	RowType_Web            RowType = 3
)

var RowType_name = map[int32]string{
	0: "Editorial",
	1: "Recommendation",
	2: "Dynamic",
	3: "Web",
}

var RowType_value = map[string]int32{
	"Editorial":      0,
	"Recommendation": 1,
	"Dynamic":        2,
	"Web":            3,
}

func (x RowType) String() string {
	return proto.EnumName(RowType_name, int32(x))
}

func (RowType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{0}
}

type RowLayout int32

const (
	RowLayout_Landscape RowLayout = 0
	RowLayout_Portrait  RowLayout = 1
	RowLayout_Square    RowLayout = 2
	RowLayout_Circle    RowLayout = 3
)

var RowLayout_name = map[int32]string{
	0: "Landscape",
	1: "Portrait",
	2: "Square",
	3: "Circle",
}

var RowLayout_value = map[string]int32{
	"Landscape": 0,
	"Portrait":  1,
	"Square":    2,
	"Circle":    3,
}

func (x RowLayout) String() string {
	return proto.EnumName(RowLayout_name, int32(x))
}

func (RowLayout) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{1}
}

// contentTile
type TileType int32

const (
	TileType_ImageTile     TileType = 0
	TileType_VideoTile     TileType = 1
	TileType_FeatureTile   TileType = 2
	TileType_AdvertiseTile TileType = 3
	TileType_CarouselTile  TileType = 4
)

var TileType_name = map[int32]string{
	0: "ImageTile",
	1: "VideoTile",
	2: "FeatureTile",
	3: "AdvertiseTile",
	4: "CarouselTile",
}

var TileType_value = map[string]int32{
	"ImageTile":     0,
	"VideoTile":     1,
	"FeatureTile":   2,
	"AdvertiseTile": 3,
	"CarouselTile":  4,
}

func (x TileType) String() string {
	return proto.EnumName(TileType_name, int32(x))
}

func (TileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{2}
}

type Schedule struct {
	Brand                string               `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Vendor               string               `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	StartTime            int32                `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int32                `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Pages                []*SchedulePage      `protobuf:"bytes,6,rep,name=pages,proto3" json:"pages,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	BaseUrl              string               `protobuf:"bytes,9,opt,name=baseUrl,proto3" json:"baseUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{0}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Schedule) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Schedule) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Schedule) GetEndTime() int32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Schedule) GetPages() []*SchedulePage {
	if m != nil {
		return m.Pages
	}
	return nil
}

func (m *Schedule) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Schedule) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Schedule) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

type SchedulePage struct {
	PageName             string               `protobuf:"bytes,1,opt,name=pageName,proto3" json:"pageName,omitempty"`
	PageIndex            int32                `protobuf:"varint,2,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageLogo             string               `protobuf:"bytes,3,opt,name=pageLogo,proto3" json:"pageLogo,omitempty"`
	Row                  []*ScheduleRow       `protobuf:"bytes,4,rep,name=row,proto3" json:"row,omitempty"`
	Carousel             []*ScheduleCarousel  `protobuf:"bytes,5,rep,name=carousel,proto3" json:"carousel,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *SchedulePage) Reset()         { *m = SchedulePage{} }
func (m *SchedulePage) String() string { return proto.CompactTextString(m) }
func (*SchedulePage) ProtoMessage()    {}
func (*SchedulePage) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{1}
}

func (m *SchedulePage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulePage.Unmarshal(m, b)
}
func (m *SchedulePage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulePage.Marshal(b, m, deterministic)
}
func (m *SchedulePage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulePage.Merge(m, src)
}
func (m *SchedulePage) XXX_Size() int {
	return xxx_messageInfo_SchedulePage.Size(m)
}
func (m *SchedulePage) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulePage.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulePage proto.InternalMessageInfo

func (m *SchedulePage) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *SchedulePage) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *SchedulePage) GetPageLogo() string {
	if m != nil {
		return m.PageLogo
	}
	return ""
}

func (m *SchedulePage) GetRow() []*ScheduleRow {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *SchedulePage) GetCarousel() []*ScheduleCarousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *SchedulePage) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SchedulePage) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ScheduleCarousel struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	PackageName          string   `protobuf:"bytes,2,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ScheduleCarousel) Reset()         { *m = ScheduleCarousel{} }
func (m *ScheduleCarousel) String() string { return proto.CompactTextString(m) }
func (*ScheduleCarousel) ProtoMessage()    {}
func (*ScheduleCarousel) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{2}
}

func (m *ScheduleCarousel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleCarousel.Unmarshal(m, b)
}
func (m *ScheduleCarousel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleCarousel.Marshal(b, m, deterministic)
}
func (m *ScheduleCarousel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleCarousel.Merge(m, src)
}
func (m *ScheduleCarousel) XXX_Size() int {
	return xxx_messageInfo_ScheduleCarousel.Size(m)
}
func (m *ScheduleCarousel) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleCarousel.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleCarousel proto.InternalMessageInfo

func (m *ScheduleCarousel) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ScheduleCarousel) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ScheduleCarousel) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *ScheduleCarousel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// -1 for sort descending and 1 for sort ascending,
type ScheduleRow struct {
	Rowlayout            RowLayout                  `protobuf:"varint,1,opt,name=rowlayout,proto3,enum=SchedularService.RowLayout" json:"rowlayout,omitempty"`
	RowName              string                     `protobuf:"bytes,2,opt,name=rowName,proto3" json:"rowName,omitempty"`
	RowIndex             int32                      `protobuf:"varint,3,opt,name=rowIndex,proto3" json:"rowIndex,omitempty"`
	RowFilters           map[string]*RowFilterValue `protobuf:"bytes,4,rep,name=rowFilters,proto3" json:"rowFilters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RowSort              map[string]int32           `protobuf:"bytes,5,rep,name=rowSort,proto3" json:"rowSort,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag32,2,opt,name=value,proto3"`
	RowTileIds           []string                   `protobuf:"bytes,6,rep,name=rowTileIds,proto3" json:"rowTileIds,omitempty"`
	RowType              RowType                    `protobuf:"varint,7,opt,name=rowType,proto3,enum=SchedularService.RowType" json:"rowType,omitempty"`
	Shuffle              bool                       `protobuf:"varint,8,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-" bson:"-"`
	XXX_unrecognized     []byte                     `json:"-" bson:"-"`
	XXX_sizecache        int32                      `json:"-" bson:"-"`
}

func (m *ScheduleRow) Reset()         { *m = ScheduleRow{} }
func (m *ScheduleRow) String() string { return proto.CompactTextString(m) }
func (*ScheduleRow) ProtoMessage()    {}
func (*ScheduleRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{3}
}

func (m *ScheduleRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleRow.Unmarshal(m, b)
}
func (m *ScheduleRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleRow.Marshal(b, m, deterministic)
}
func (m *ScheduleRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleRow.Merge(m, src)
}
func (m *ScheduleRow) XXX_Size() int {
	return xxx_messageInfo_ScheduleRow.Size(m)
}
func (m *ScheduleRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleRow.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleRow proto.InternalMessageInfo

func (m *ScheduleRow) GetRowlayout() RowLayout {
	if m != nil {
		return m.Rowlayout
	}
	return RowLayout_Landscape
}

func (m *ScheduleRow) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *ScheduleRow) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

func (m *ScheduleRow) GetRowFilters() map[string]*RowFilterValue {
	if m != nil {
		return m.RowFilters
	}
	return nil
}

func (m *ScheduleRow) GetRowSort() map[string]int32 {
	if m != nil {
		return m.RowSort
	}
	return nil
}

func (m *ScheduleRow) GetRowTileIds() []string {
	if m != nil {
		return m.RowTileIds
	}
	return nil
}

func (m *ScheduleRow) GetRowType() RowType {
	if m != nil {
		return m.RowType
	}
	return RowType_Editorial
}

func (m *ScheduleRow) GetShuffle() bool {
	if m != nil {
		return m.Shuffle
	}
	return false
}

type RowFilterValue struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RowFilterValue) Reset()         { *m = RowFilterValue{} }
func (m *RowFilterValue) String() string { return proto.CompactTextString(m) }
func (*RowFilterValue) ProtoMessage()    {}
func (*RowFilterValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{4}
}

func (m *RowFilterValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowFilterValue.Unmarshal(m, b)
}
func (m *RowFilterValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowFilterValue.Marshal(b, m, deterministic)
}
func (m *RowFilterValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowFilterValue.Merge(m, src)
}
func (m *RowFilterValue) XXX_Size() int {
	return xxx_messageInfo_RowFilterValue.Size(m)
}
func (m *RowFilterValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RowFilterValue.DiscardUnknown(m)
}

var xxx_messageInfo_RowFilterValue proto.InternalMessageInfo

func (m *RowFilterValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetScheduleRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetScheduleRequest) Reset()         { *m = GetScheduleRequest{} }
func (m *GetScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*GetScheduleRequest) ProtoMessage()    {}
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{5}
}

func (m *GetScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScheduleRequest.Unmarshal(m, b)
}
func (m *GetScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScheduleRequest.Marshal(b, m, deterministic)
}
func (m *GetScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScheduleRequest.Merge(m, src)
}
func (m *GetScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_GetScheduleRequest.Size(m)
}
func (m *GetScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetScheduleRequest proto.InternalMessageInfo

func (m *GetScheduleRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *GetScheduleRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type DeleteScheduleRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	StartTime            int32    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int32    `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteScheduleRequest) Reset()         { *m = DeleteScheduleRequest{} }
func (m *DeleteScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteScheduleRequest) ProtoMessage()    {}
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{6}
}

func (m *DeleteScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteScheduleRequest.Unmarshal(m, b)
}
func (m *DeleteScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteScheduleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteScheduleRequest.Merge(m, src)
}
func (m *DeleteScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteScheduleRequest.Size(m)
}
func (m *DeleteScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteScheduleRequest proto.InternalMessageInfo

func (m *DeleteScheduleRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *DeleteScheduleRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *DeleteScheduleRequest) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *DeleteScheduleRequest) GetEndTime() int32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type DeleteScheduleResponse struct {
	IsSuccessful         bool     `protobuf:"varint,1,opt,name=isSuccessful,proto3" json:"isSuccessful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteScheduleResponse) Reset()         { *m = DeleteScheduleResponse{} }
func (m *DeleteScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteScheduleResponse) ProtoMessage()    {}
func (*DeleteScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{7}
}

func (m *DeleteScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteScheduleResponse.Unmarshal(m, b)
}
func (m *DeleteScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteScheduleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteScheduleResponse.Merge(m, src)
}
func (m *DeleteScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteScheduleResponse.Size(m)
}
func (m *DeleteScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteScheduleResponse proto.InternalMessageInfo

func (m *DeleteScheduleResponse) GetIsSuccessful() bool {
	if m != nil {
		return m.IsSuccessful
	}
	return false
}

//Refresh logic
type RefreshScheduleRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	StartTime            int32    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int32    `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RefreshScheduleRequest) Reset()         { *m = RefreshScheduleRequest{} }
func (m *RefreshScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshScheduleRequest) ProtoMessage()    {}
func (*RefreshScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{8}
}

func (m *RefreshScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshScheduleRequest.Unmarshal(m, b)
}
func (m *RefreshScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshScheduleRequest.Marshal(b, m, deterministic)
}
func (m *RefreshScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshScheduleRequest.Merge(m, src)
}
func (m *RefreshScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshScheduleRequest.Size(m)
}
func (m *RefreshScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshScheduleRequest proto.InternalMessageInfo

func (m *RefreshScheduleRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *RefreshScheduleRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *RefreshScheduleRequest) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RefreshScheduleRequest) GetEndTime() int32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type RefreshScheduleResponse struct {
	IsSuccessful         bool     `protobuf:"varint,1,opt,name=isSuccessful,proto3" json:"isSuccessful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RefreshScheduleResponse) Reset()         { *m = RefreshScheduleResponse{} }
func (m *RefreshScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshScheduleResponse) ProtoMessage()    {}
func (*RefreshScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{9}
}

func (m *RefreshScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshScheduleResponse.Unmarshal(m, b)
}
func (m *RefreshScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshScheduleResponse.Marshal(b, m, deterministic)
}
func (m *RefreshScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshScheduleResponse.Merge(m, src)
}
func (m *RefreshScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshScheduleResponse.Size(m)
}
func (m *RefreshScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshScheduleResponse proto.InternalMessageInfo

func (m *RefreshScheduleResponse) GetIsSuccessful() bool {
	if m != nil {
		return m.IsSuccessful
	}
	return false
}

// Row
type Row struct {
	RowName              string    `protobuf:"bytes,1,opt,name=rowName,proto3" json:"rowName,omitempty"`
	RowLayout            RowLayout `protobuf:"varint,2,opt,name=rowLayout,proto3,enum=SchedularService.RowLayout" json:"rowLayout,omitempty"`
	ContentBaseUrl       string    `protobuf:"bytes,3,opt,name=contentBaseUrl,proto3" json:"contentBaseUrl,omitempty"`
	ContentId            string    `protobuf:"bytes,4,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Shuffle              bool      `protobuf:"varint,5,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
	RowIndex             int32     `protobuf:"varint,6,opt,name=rowIndex,proto3" json:"rowIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{10}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *Row) GetRowLayout() RowLayout {
	if m != nil {
		return m.RowLayout
	}
	return RowLayout_Landscape
}

func (m *Row) GetContentBaseUrl() string {
	if m != nil {
		return m.ContentBaseUrl
	}
	return ""
}

func (m *Row) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *Row) GetShuffle() bool {
	if m != nil {
		return m.Shuffle
	}
	return false
}

func (m *Row) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

type ContentTile struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	MediaUrl             string   `protobuf:"bytes,2,opt,name=mediaUrl,proto3" json:"mediaUrl,omitempty"`
	TileType             TileType `protobuf:"varint,3,opt,name=tileType,proto3,enum=SchedularService.TileType" json:"tileType,omitempty"`
	Poster               string   `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	Portrait             string   `protobuf:"bytes,5,opt,name=portrait,proto3" json:"portrait,omitempty"`
	IsDetailPage         bool     `protobuf:"varint,6,opt,name=isDetailPage,proto3" json:"isDetailPage,omitempty"`
	PackageName          string   `protobuf:"bytes,7,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ContentId            string   `protobuf:"bytes,8,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Target               []string `protobuf:"bytes,9,rep,name=target,proto3" json:"target,omitempty"`
	RealeaseDate         string   `protobuf:"bytes,10,opt,name=realeaseDate,proto3" json:"realeaseDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ContentTile) Reset()         { *m = ContentTile{} }
func (m *ContentTile) String() string { return proto.CompactTextString(m) }
func (*ContentTile) ProtoMessage()    {}
func (*ContentTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{11}
}

func (m *ContentTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentTile.Unmarshal(m, b)
}
func (m *ContentTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentTile.Marshal(b, m, deterministic)
}
func (m *ContentTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentTile.Merge(m, src)
}
func (m *ContentTile) XXX_Size() int {
	return xxx_messageInfo_ContentTile.Size(m)
}
func (m *ContentTile) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentTile.DiscardUnknown(m)
}

var xxx_messageInfo_ContentTile proto.InternalMessageInfo

func (m *ContentTile) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ContentTile) GetMediaUrl() string {
	if m != nil {
		return m.MediaUrl
	}
	return ""
}

func (m *ContentTile) GetTileType() TileType {
	if m != nil {
		return m.TileType
	}
	return TileType_ImageTile
}

func (m *ContentTile) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *ContentTile) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *ContentTile) GetIsDetailPage() bool {
	if m != nil {
		return m.IsDetailPage
	}
	return false
}

func (m *ContentTile) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ContentTile) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *ContentTile) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *ContentTile) GetRealeaseDate() string {
	if m != nil {
		return m.RealeaseDate
	}
	return ""
}

//carosuel
type CarouselResponse struct {
	Carousel             []*Carousel `protobuf:"bytes,1,rep,name=carousel,proto3" json:"carousel,omitempty"`
	CarouselBaseUrl      string      `protobuf:"bytes,2,opt,name=carouselBaseUrl,proto3" json:"carouselBaseUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *CarouselResponse) Reset()         { *m = CarouselResponse{} }
func (m *CarouselResponse) String() string { return proto.CompactTextString(m) }
func (*CarouselResponse) ProtoMessage()    {}
func (*CarouselResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{12}
}

func (m *CarouselResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarouselResponse.Unmarshal(m, b)
}
func (m *CarouselResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarouselResponse.Marshal(b, m, deterministic)
}
func (m *CarouselResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarouselResponse.Merge(m, src)
}
func (m *CarouselResponse) XXX_Size() int {
	return xxx_messageInfo_CarouselResponse.Size(m)
}
func (m *CarouselResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CarouselResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CarouselResponse proto.InternalMessageInfo

func (m *CarouselResponse) GetCarousel() []*Carousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *CarouselResponse) GetCarouselBaseUrl() string {
	if m != nil {
		return m.CarouselBaseUrl
	}
	return ""
}

type Carousel struct {
	ImageUrl             string   `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PackageName          string   `protobuf:"bytes,4,opt,name=packageName,proto3" json:"packageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Carousel) Reset()         { *m = Carousel{} }
func (m *Carousel) String() string { return proto.CompactTextString(m) }
func (*Carousel) ProtoMessage()    {}
func (*Carousel) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{13}
}

func (m *Carousel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carousel.Unmarshal(m, b)
}
func (m *Carousel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carousel.Marshal(b, m, deterministic)
}
func (m *Carousel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carousel.Merge(m, src)
}
func (m *Carousel) XXX_Size() int {
	return xxx_messageInfo_Carousel.Size(m)
}
func (m *Carousel) XXX_DiscardUnknown() {
	xxx_messageInfo_Carousel.DiscardUnknown(m)
}

var xxx_messageInfo_Carousel proto.InternalMessageInfo

func (m *Carousel) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Carousel) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Carousel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Carousel) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

//Page
type CloudwalkerSchedule struct {
	PrimePages           []*PrimePage `protobuf:"bytes,1,rep,name=primePages,proto3" json:"primePages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" bson:"-"`
}

func (m *CloudwalkerSchedule) Reset()         { *m = CloudwalkerSchedule{} }
func (m *CloudwalkerSchedule) String() string { return proto.CompactTextString(m) }
func (*CloudwalkerSchedule) ProtoMessage()    {}
func (*CloudwalkerSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{14}
}

func (m *CloudwalkerSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudwalkerSchedule.Unmarshal(m, b)
}
func (m *CloudwalkerSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudwalkerSchedule.Marshal(b, m, deterministic)
}
func (m *CloudwalkerSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudwalkerSchedule.Merge(m, src)
}
func (m *CloudwalkerSchedule) XXX_Size() int {
	return xxx_messageInfo_CloudwalkerSchedule.Size(m)
}
func (m *CloudwalkerSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudwalkerSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_CloudwalkerSchedule proto.InternalMessageInfo

func (m *CloudwalkerSchedule) GetPrimePages() []*PrimePage {
	if m != nil {
		return m.PrimePages
	}
	return nil
}

type PrimePage struct {
	PageName             string   `protobuf:"bytes,1,opt,name=pageName,proto3" json:"pageName,omitempty"`
	PageEndpoint         string   `protobuf:"bytes,2,opt,name=pageEndpoint,proto3" json:"pageEndpoint,omitempty"`
	PageIndex            int32    `protobuf:"varint,3,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PrimePage) Reset()         { *m = PrimePage{} }
func (m *PrimePage) String() string { return proto.CompactTextString(m) }
func (*PrimePage) ProtoMessage()    {}
func (*PrimePage) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{15}
}

func (m *PrimePage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimePage.Unmarshal(m, b)
}
func (m *PrimePage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimePage.Marshal(b, m, deterministic)
}
func (m *PrimePage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimePage.Merge(m, src)
}
func (m *PrimePage) XXX_Size() int {
	return xxx_messageInfo_PrimePage.Size(m)
}
func (m *PrimePage) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimePage.DiscardUnknown(m)
}

var xxx_messageInfo_PrimePage proto.InternalMessageInfo

func (m *PrimePage) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *PrimePage) GetPageEndpoint() string {
	if m != nil {
		return m.PageEndpoint
	}
	return ""
}

func (m *PrimePage) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

type Page struct {
	CarouselEndpoint     string   `protobuf:"bytes,1,opt,name=carouselEndpoint,proto3" json:"carouselEndpoint,omitempty"`
	RowContentEndpoint   []string `protobuf:"bytes,2,rep,name=rowContentEndpoint,proto3" json:"rowContentEndpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{16}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetCarouselEndpoint() string {
	if m != nil {
		return m.CarouselEndpoint
	}
	return ""
}

func (m *Page) GetRowContentEndpoint() []string {
	if m != nil {
		return m.RowContentEndpoint
	}
	return nil
}

func init() {
	proto.RegisterEnum("SchedularService.RowType", RowType_name, RowType_value)
	proto.RegisterEnum("SchedularService.RowLayout", RowLayout_name, RowLayout_value)
	proto.RegisterEnum("SchedularService.TileType", TileType_name, TileType_value)
	proto.RegisterType((*Schedule)(nil), "SchedularService.Schedule")
	proto.RegisterType((*SchedulePage)(nil), "SchedularService.SchedulePage")
	proto.RegisterType((*ScheduleCarousel)(nil), "SchedularService.ScheduleCarousel")
	proto.RegisterType((*ScheduleRow)(nil), "SchedularService.ScheduleRow")
	proto.RegisterMapType((map[string]*RowFilterValue)(nil), "SchedularService.ScheduleRow.RowFiltersEntry")
	proto.RegisterMapType((map[string]int32)(nil), "SchedularService.ScheduleRow.RowSortEntry")
	proto.RegisterType((*RowFilterValue)(nil), "SchedularService.RowFilterValue")
	proto.RegisterType((*GetScheduleRequest)(nil), "SchedularService.GetScheduleRequest")
	proto.RegisterType((*DeleteScheduleRequest)(nil), "SchedularService.DeleteScheduleRequest")
	proto.RegisterType((*DeleteScheduleResponse)(nil), "SchedularService.DeleteScheduleResponse")
	proto.RegisterType((*RefreshScheduleRequest)(nil), "SchedularService.RefreshScheduleRequest")
	proto.RegisterType((*RefreshScheduleResponse)(nil), "SchedularService.RefreshScheduleResponse")
	proto.RegisterType((*Row)(nil), "SchedularService.Row")
	proto.RegisterType((*ContentTile)(nil), "SchedularService.ContentTile")
	proto.RegisterType((*CarouselResponse)(nil), "SchedularService.CarouselResponse")
	proto.RegisterType((*Carousel)(nil), "SchedularService.Carousel")
	proto.RegisterType((*CloudwalkerSchedule)(nil), "SchedularService.CloudwalkerSchedule")
	proto.RegisterType((*PrimePage)(nil), "SchedularService.PrimePage")
	proto.RegisterType((*Page)(nil), "SchedularService.Page")
}

func init() { proto.RegisterFile("SchedularService.proto", fileDescriptor_199c4d2fc282de6a) }

var fileDescriptor_199c4d2fc282de6a = []byte{
	// 1321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0xee, 0xfa, 0x92, 0xd8, 0xc7, 0xae, 0xb3, 0x1d, 0xda, 0xe0, 0x9a, 0xb6, 0x58, 0x4b, 0x05,
	0xc6, 0x12, 0x09, 0x4a, 0x51, 0x55, 0xc2, 0x45, 0xb4, 0x49, 0x8b, 0x22, 0x15, 0x54, 0x6d, 0xd2,
	0xf2, 0x06, 0x1a, 0xef, 0x9e, 0xb8, 0xab, 0xae, 0x77, 0xdc, 0xd9, 0xd9, 0x98, 0x3c, 0xd0, 0x07,
	0x9e, 0x78, 0xe0, 0x8d, 0x1f, 0xc0, 0x9f, 0xe0, 0x4f, 0x20, 0x1e, 0x91, 0xf8, 0x05, 0xfc, 0x0f,
	0xd0, 0x5c, 0xf6, 0x6a, 0x37, 0x2d, 0x20, 0xd4, 0xb7, 0x3d, 0x67, 0xce, 0xf5, 0x9b, 0x73, 0x99,
	0x85, 0xcd, 0x43, 0xef, 0x31, 0xfa, 0x49, 0x48, 0xf9, 0x21, 0xf2, 0x93, 0xc0, 0xc3, 0xad, 0x39,
	0x67, 0x82, 0x11, 0xbb, 0xca, 0x1f, 0xbc, 0x39, 0x65, 0x6c, 0x1a, 0xe2, 0xb6, 0x3a, 0x9f, 0x24,
	0xc7, 0xdb, 0x22, 0x98, 0x61, 0x2c, 0xe8, 0x6c, 0xae, 0x55, 0x06, 0x57, 0x8c, 0x00, 0x9d, 0x07,
	0xdb, 0x34, 0x8a, 0x98, 0xa0, 0x22, 0x60, 0x51, 0xac, 0x4f, 0x9d, 0x5f, 0x6a, 0xd0, 0x32, 0x36,
	0x91, 0x5c, 0x84, 0xe6, 0x84, 0xd3, 0xc8, 0xef, 0x5b, 0x43, 0x6b, 0xd4, 0x76, 0x35, 0x41, 0x36,
	0x61, 0xed, 0x04, 0x23, 0x9f, 0xf1, 0x7e, 0x4d, 0xb1, 0x0d, 0x45, 0xae, 0x40, 0x3b, 0x16, 0x94,
	0x8b, 0xa3, 0x60, 0x86, 0xfd, 0xfa, 0xd0, 0x1a, 0x35, 0xdd, 0x9c, 0x41, 0xfa, 0xb0, 0x8e, 0x91,
	0xaf, 0xce, 0x1a, 0xea, 0x2c, 0x25, 0xc9, 0x07, 0xd0, 0x9c, 0xd3, 0x29, 0xc6, 0xfd, 0xb5, 0x61,
	0x7d, 0xd4, 0xd9, 0xb9, 0xb6, 0xb5, 0x94, 0x6b, 0x1a, 0xd0, 0x03, 0x3a, 0x45, 0x57, 0x0b, 0x93,
	0x5b, 0xd0, 0xf6, 0x38, 0x52, 0x81, 0xfe, 0x6d, 0xd1, 0x5f, 0x1f, 0x5a, 0xa3, 0xce, 0xce, 0x60,
	0x4b, 0xa7, 0xb6, 0x95, 0xe6, 0xbe, 0x75, 0x94, 0xe6, 0xee, 0xe6, 0xc2, 0x52, 0x33, 0x99, 0xfb,
	0x46, 0xb3, 0xf5, 0x62, 0xcd, 0x4c, 0x58, 0xe6, 0x30, 0xa1, 0x31, 0x3e, 0xe4, 0x61, 0xbf, 0xad,
	0x52, 0x4f, 0x49, 0xe7, 0xd7, 0x1a, 0x74, 0x8b, 0x51, 0x92, 0x01, 0xb4, 0x64, 0x9c, 0x5f, 0xd2,
	0x19, 0x1a, 0xf4, 0x32, 0x5a, 0x02, 0x25, 0xbf, 0x0f, 0x22, 0x1f, 0xbf, 0x55, 0x18, 0x36, 0xdd,
	0x9c, 0x91, 0x6a, 0xde, 0x67, 0x53, 0xa6, 0x50, 0x34, 0x9a, 0x92, 0x26, 0xdb, 0x50, 0xe7, 0x6c,
	0xd1, 0x6f, 0x28, 0xa0, 0xae, 0x3e, 0x1f, 0x28, 0x97, 0x2d, 0x5c, 0x29, 0x49, 0x3e, 0x85, 0x96,
	0x47, 0x39, 0x4b, 0x62, 0x0c, 0xfb, 0x4d, 0xa5, 0xe5, 0x3c, 0x5f, 0x6b, 0xcf, 0x48, 0xba, 0x99,
	0xce, 0xab, 0x40, 0xd9, 0x79, 0x06, 0x76, 0x35, 0x22, 0x59, 0x73, 0x82, 0xf2, 0x29, 0x0a, 0x03,
	0xa6, 0xa1, 0xc8, 0x10, 0x3a, 0x73, 0xea, 0x3d, 0x49, 0x91, 0xd6, 0x05, 0x59, 0x64, 0x49, 0x38,
	0x83, 0x19, 0x9d, 0xaa, 0x4b, 0x33, 0x70, 0xa6, 0xb4, 0xac, 0x6f, 0x11, 0x88, 0x50, 0x57, 0x64,
	0xdb, 0xd5, 0x84, 0xf3, 0x73, 0x03, 0x3a, 0x05, 0x20, 0xc9, 0x87, 0xd0, 0xe6, 0x6c, 0x11, 0xd2,
	0x53, 0x96, 0x68, 0xf7, 0xbd, 0x9d, 0x37, 0x96, 0x41, 0x74, 0xd9, 0xe2, 0xbe, 0x12, 0x71, 0x73,
	0x69, 0x59, 0x30, 0x9c, 0x2d, 0x0a, 0xa1, 0xa5, 0xa4, 0x0c, 0x8b, 0xb3, 0x85, 0x2e, 0x01, 0xdd,
	0x2b, 0x19, 0x4d, 0xbe, 0x00, 0xe0, 0x6c, 0x71, 0x2f, 0x08, 0x05, 0xf2, 0xd8, 0x5c, 0xf6, 0x7b,
	0x67, 0x5e, 0xb6, 0xf4, 0x6e, 0xe4, 0xef, 0x46, 0x82, 0x9f, 0xba, 0x05, 0x03, 0x64, 0x5f, 0x05,
	0x71, 0xc8, 0xb8, 0x30, 0x25, 0x30, 0x7e, 0xa1, 0x2d, 0x29, 0xac, 0x0d, 0xa5, 0xaa, 0xe4, 0x9a,
	0x0a, 0xea, 0x28, 0x08, 0xf1, 0xc0, 0xd7, 0xad, 0xda, 0x76, 0x0b, 0x1c, 0x72, 0x43, 0x79, 0x39,
	0x3a, 0x9d, 0xa3, 0xaa, 0x93, 0xde, 0xce, 0xe5, 0x95, 0x18, 0x49, 0x01, 0x37, 0x95, 0x94, 0xf8,
	0xc4, 0x8f, 0x93, 0xe3, 0xe3, 0x10, 0x55, 0x89, 0xb4, 0xdc, 0x94, 0x1c, 0x7c, 0x03, 0x1b, 0x95,
	0x9c, 0x88, 0x0d, 0xf5, 0x27, 0x78, 0x6a, 0x0a, 0x40, 0x7e, 0x92, 0x9b, 0xd0, 0x3c, 0xa1, 0x61,
	0xa2, 0xc1, 0xed, 0xec, 0x0c, 0x57, 0x7a, 0xd4, 0x36, 0x1e, 0x49, 0x39, 0x57, 0x8b, 0xef, 0xd6,
	0x6e, 0x59, 0x83, 0x5d, 0xe8, 0x16, 0x13, 0x5d, 0x61, 0xfd, 0x62, 0xd1, 0xfa, 0x85, 0x82, 0xae,
	0x33, 0x82, 0x5e, 0xd9, 0xb0, 0x9a, 0x89, 0xf2, 0x23, 0xee, 0x5b, 0x0a, 0x19, 0x43, 0x39, 0x77,
	0x80, 0x7c, 0x8e, 0x22, 0x43, 0x17, 0x9f, 0x26, 0x18, 0x8b, 0xc2, 0x04, 0xb5, 0x4a, 0x13, 0x34,
	0x9b, 0xb7, 0xb5, 0xc2, 0xbc, 0x75, 0xbe, 0x83, 0x4b, 0xfb, 0x18, 0xa2, 0xc0, 0xff, 0x64, 0xe6,
	0xdf, 0x8e, 0x67, 0xe7, 0x63, 0xd8, 0xac, 0xba, 0x8f, 0xe7, 0x2c, 0x8a, 0x91, 0x38, 0xd0, 0x0d,
	0xe2, 0xc3, 0xc4, 0xf3, 0x30, 0x8e, 0x8f, 0x93, 0x50, 0x45, 0xd1, 0x72, 0x4b, 0x3c, 0xe7, 0x19,
	0x6c, 0xba, 0x78, 0xcc, 0x31, 0x7e, 0xfc, 0x6a, 0xa2, 0xff, 0x04, 0x5e, 0x5f, 0xf2, 0xff, 0x0f,
	0xc2, 0xff, 0xc3, 0x82, 0xba, 0x9c, 0x01, 0x85, 0x46, 0xb6, 0xca, 0x8d, 0xac, 0xa7, 0x83, 0x6e,
	0x7d, 0x15, 0xf2, 0x4b, 0x4c, 0x07, 0xfd, 0x49, 0xde, 0x86, 0x9e, 0xc7, 0x22, 0x81, 0x91, 0xb8,
	0x63, 0xb6, 0x8a, 0x1e, 0x50, 0x15, 0xae, 0xcc, 0xdd, 0x70, 0x0e, 0x7c, 0x33, 0xaa, 0x72, 0x46,
	0xb1, 0x87, 0x9a, 0xa5, 0x1e, 0x2a, 0xcd, 0x98, 0xb5, 0xf2, 0x8c, 0x71, 0x7e, 0xab, 0x41, 0x67,
	0x4f, 0xdb, 0x90, 0x1d, 0x9c, 0x8f, 0x42, 0xab, 0x30, 0x0a, 0xa5, 0x85, 0x19, 0xfa, 0x01, 0x95,
	0xb1, 0xe9, 0xeb, 0xc8, 0x68, 0x72, 0x13, 0x5a, 0x22, 0x08, 0x51, 0x75, 0x7c, 0x5d, 0xe5, 0x3d,
	0x58, 0xce, 0xfb, 0xc8, 0x48, 0xb8, 0x99, 0xac, 0xbc, 0xf7, 0x39, 0x8b, 0x05, 0x72, 0x93, 0x8a,
	0xa1, 0xd4, 0xde, 0x63, 0x5c, 0x70, 0x1a, 0x08, 0x95, 0x88, 0xdc, 0x7b, 0x86, 0xd6, 0x57, 0xb5,
	0x8f, 0x82, 0x06, 0xa1, 0xdc, 0xae, 0x2a, 0x1b, 0x75, 0x55, 0x39, 0xaf, 0xba, 0x0a, 0xd6, 0x97,
	0x57, 0x41, 0x09, 0xc7, 0x56, 0x15, 0xc7, 0x7c, 0xc5, 0xb4, 0x75, 0x0b, 0x9b, 0x15, 0xe3, 0x40,
	0x97, 0x23, 0x0d, 0x91, 0xc6, 0xb8, 0x4f, 0x05, 0xf6, 0x41, 0x29, 0x96, 0x78, 0x8e, 0x00, 0x3b,
	0x5b, 0x9e, 0x69, 0x79, 0xdd, 0x2c, 0xac, 0x5e, 0x4b, 0xcd, 0xdd, 0x15, 0xf8, 0xac, 0x58, 0xb9,
	0x23, 0xd8, 0x48, 0xbf, 0xd3, 0xb2, 0xd0, 0xd0, 0x57, 0xd9, 0xce, 0x09, 0xb4, 0xb2, 0x05, 0x59,
	0x5c, 0x73, 0x56, 0x65, 0xcd, 0xe5, 0x99, 0xd5, 0x4a, 0xcb, 0x33, 0xbb, 0xf3, 0x7a, 0xf1, 0xce,
	0x2b, 0x38, 0x36, 0x96, 0x70, 0x74, 0x5c, 0x78, 0x6d, 0x2f, 0x64, 0x89, 0xbf, 0xa0, 0xe1, 0x13,
	0xe4, 0xd9, 0x6b, 0xf1, 0x23, 0x80, 0x39, 0x0f, 0x66, 0xea, 0xfd, 0x13, 0x9b, 0x94, 0x57, 0xb4,
	0xc2, 0x83, 0x54, 0xc6, 0x2d, 0x88, 0x3b, 0x01, 0xb4, 0xb3, 0x83, 0x33, 0x1f, 0x4f, 0x0e, 0x74,
	0xe5, 0xf7, 0xdd, 0xc8, 0x9f, 0xb3, 0x20, 0x4a, 0x53, 0x2a, 0xf1, 0xca, 0x0f, 0xac, 0x7a, 0xe5,
	0x81, 0xe5, 0x4c, 0xa0, 0xa1, 0xbc, 0x8c, 0xc1, 0x4e, 0x11, 0xcd, 0xac, 0x69, 0x6f, 0x4b, 0x7c,
	0xb2, 0x05, 0x84, 0xb3, 0x85, 0x69, 0x98, 0x82, 0x6f, 0x59, 0x28, 0x2b, 0x4e, 0xc6, 0x77, 0x60,
	0xdd, 0x2c, 0x3b, 0x72, 0x1e, 0xda, 0x77, 0xfd, 0x40, 0x30, 0x1e, 0xd0, 0xd0, 0x3e, 0x47, 0x08,
	0xf4, 0x5c, 0xf4, 0xd8, 0x6c, 0x86, 0x91, 0xaf, 0x5e, 0xde, 0xb6, 0x45, 0x3a, 0xb0, 0xbe, 0x7f,
	0x1a, 0xd1, 0x59, 0xe0, 0xd9, 0x35, 0xb2, 0x0e, 0xf5, 0xaf, 0x70, 0x62, 0xd7, 0xc7, 0x9f, 0x41,
	0x3b, 0x1b, 0x1b, 0xd2, 0xca, 0x7d, 0x1a, 0xf9, 0xb1, 0x47, 0xe7, 0x68, 0x9f, 0x23, 0x5d, 0x68,
	0x3d, 0x30, 0xcd, 0x61, 0x5b, 0x04, 0x60, 0xed, 0xf0, 0x69, 0x42, 0x39, 0xda, 0x35, 0xf9, 0xbd,
	0x17, 0x70, 0x2f, 0x44, 0xbb, 0x3e, 0xfe, 0x1a, 0x5a, 0x69, 0x03, 0x4a, 0x03, 0x07, 0xb2, 0x20,
	0x24, 0xc3, 0x3e, 0x27, 0xc9, 0x47, 0x81, 0x8f, 0x4c, 0x91, 0x16, 0xd9, 0x80, 0xce, 0x3d, 0xa4,
	0x22, 0xe1, 0xfa, 0xbc, 0x46, 0x2e, 0xc0, 0xf9, 0xdb, 0xfe, 0x09, 0x72, 0x11, 0xc4, 0x9a, 0x55,
	0x27, 0x36, 0x74, 0xd3, 0x72, 0x53, 0x9c, 0xc6, 0xce, 0x5f, 0x0d, 0x58, 0xfa, 0x01, 0x21, 0x33,
	0xe8, 0xed, 0xa9, 0x57, 0x60, 0x56, 0x18, 0x83, 0xe7, 0xbf, 0x37, 0x06, 0x67, 0x9c, 0x39, 0x6f,
	0x7d, 0xff, 0xfb, 0x9f, 0x3f, 0xd5, 0xae, 0x3a, 0xfd, 0xed, 0xd8, 0xb0, 0xb6, 0xbd, 0x92, 0xe5,
	0x5d, 0x6b, 0x4c, 0x62, 0xe8, 0x14, 0x36, 0x2c, 0xb9, 0xbe, 0x6c, 0x6f, 0x79, 0x01, 0x9f, 0xe9,
	0x75, 0xa8, 0xbc, 0x0e, 0x9c, 0x4b, 0xb9, 0xd7, 0x69, 0x6e, 0x61, 0xd7, 0x1a, 0xbf, 0x6f, 0xc9,
	0x1c, 0x1f, 0xaa, 0xf7, 0xea, 0xff, 0x91, 0x63, 0x52, 0xb2, 0x2c, 0x73, 0xfc, 0xc1, 0x82, 0x5e,
	0x79, 0x07, 0x93, 0x77, 0x96, 0x6d, 0xae, 0x7c, 0x24, 0x0c, 0x46, 0x2f, 0x16, 0xd4, 0x03, 0x6b,
	0x55, 0x28, 0x7e, 0x49, 0x52, 0x86, 0xf2, 0xa3, 0x05, 0x1b, 0x95, 0x85, 0x4a, 0x56, 0xb8, 0x58,
	0xbd, 0xf3, 0x07, 0xef, 0xbe, 0x84, 0xa4, 0x89, 0xe6, 0xba, 0x8a, 0xe6, 0x9a, 0x73, 0x39, 0x8f,
	0x86, 0x97, 0x45, 0x77, 0xad, 0xf1, 0x64, 0x4d, 0xfd, 0x4a, 0xdc, 0xf8, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x10, 0x64, 0x0c, 0x66, 0x20, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedularServiceClient is the client API for SchedularService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedularServiceClient interface {
	//Schedular CRUD
	CreateSchedule(ctx context.Context, in *Schedule, opts ...grpc.CallOption) (*Schedule, error)
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (SchedularService_GetScheduleClient, error)
	UpdateSchedule(ctx context.Context, in *Schedule, opts ...grpc.CallOption) (*Schedule, error)
	DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error)
	//Refresh manupilation
	RefreshSchedule(ctx context.Context, in *RefreshScheduleRequest, opts ...grpc.CallOption) (*RefreshScheduleResponse, error)
}

type schedularServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchedularServiceClient(cc *grpc.ClientConn) SchedularServiceClient {
	return &schedularServiceClient{cc}
}

func (c *schedularServiceClient) CreateSchedule(ctx context.Context, in *Schedule, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := c.cc.Invoke(ctx, "/SchedularService.SchedularService/CreateSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedularServiceClient) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (SchedularService_GetScheduleClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SchedularService_serviceDesc.Streams[0], "/SchedularService.SchedularService/GetSchedule", opts...)
	if err != nil {
		return nil, err
	}
	x := &schedularServiceGetScheduleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SchedularService_GetScheduleClient interface {
	Recv() (*Schedule, error)
	grpc.ClientStream
}

type schedularServiceGetScheduleClient struct {
	grpc.ClientStream
}

func (x *schedularServiceGetScheduleClient) Recv() (*Schedule, error) {
	m := new(Schedule)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *schedularServiceClient) UpdateSchedule(ctx context.Context, in *Schedule, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := c.cc.Invoke(ctx, "/SchedularService.SchedularService/UpdateSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedularServiceClient) DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error) {
	out := new(DeleteScheduleResponse)
	err := c.cc.Invoke(ctx, "/SchedularService.SchedularService/DeleteSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedularServiceClient) RefreshSchedule(ctx context.Context, in *RefreshScheduleRequest, opts ...grpc.CallOption) (*RefreshScheduleResponse, error) {
	out := new(RefreshScheduleResponse)
	err := c.cc.Invoke(ctx, "/SchedularService.SchedularService/RefreshSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedularServiceServer is the server API for SchedularService service.
type SchedularServiceServer interface {
	//Schedular CRUD
	CreateSchedule(context.Context, *Schedule) (*Schedule, error)
	GetSchedule(*GetScheduleRequest, SchedularService_GetScheduleServer) error
	UpdateSchedule(context.Context, *Schedule) (*Schedule, error)
	DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	//Refresh manupilation
	RefreshSchedule(context.Context, *RefreshScheduleRequest) (*RefreshScheduleResponse, error)
}

// UnimplementedSchedularServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSchedularServiceServer struct {
}

func (*UnimplementedSchedularServiceServer) CreateSchedule(ctx context.Context, req *Schedule) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (*UnimplementedSchedularServiceServer) GetSchedule(req *GetScheduleRequest, srv SchedularService_GetScheduleServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSchedule not implemented")
}
func (*UnimplementedSchedularServiceServer) UpdateSchedule(ctx context.Context, req *Schedule) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSchedule not implemented")
}
func (*UnimplementedSchedularServiceServer) DeleteSchedule(ctx context.Context, req *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (*UnimplementedSchedularServiceServer) RefreshSchedule(ctx context.Context, req *RefreshScheduleRequest) (*RefreshScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSchedule not implemented")
}

func RegisterSchedularServiceServer(s *grpc.Server, srv SchedularServiceServer) {
	s.RegisterService(&_SchedularService_serviceDesc, srv)
}

func _SchedularService_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Schedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedularServiceServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SchedularService.SchedularService/CreateSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedularServiceServer).CreateSchedule(ctx, req.(*Schedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedularService_GetSchedule_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetScheduleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchedularServiceServer).GetSchedule(m, &schedularServiceGetScheduleServer{stream})
}

type SchedularService_GetScheduleServer interface {
	Send(*Schedule) error
	grpc.ServerStream
}

type schedularServiceGetScheduleServer struct {
	grpc.ServerStream
}

func (x *schedularServiceGetScheduleServer) Send(m *Schedule) error {
	return x.ServerStream.SendMsg(m)
}

func _SchedularService_UpdateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Schedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedularServiceServer).UpdateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SchedularService.SchedularService/UpdateSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedularServiceServer).UpdateSchedule(ctx, req.(*Schedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedularService_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedularServiceServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SchedularService.SchedularService/DeleteSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedularServiceServer).DeleteSchedule(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedularService_RefreshSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedularServiceServer).RefreshSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SchedularService.SchedularService/RefreshSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedularServiceServer).RefreshSchedule(ctx, req.(*RefreshScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchedularService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SchedularService.SchedularService",
	HandlerType: (*SchedularServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSchedule",
			Handler:    _SchedularService_CreateSchedule_Handler,
		},
		{
			MethodName: "UpdateSchedule",
			Handler:    _SchedularService_UpdateSchedule_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _SchedularService_DeleteSchedule_Handler,
		},
		{
			MethodName: "RefreshSchedule",
			Handler:    _SchedularService_RefreshSchedule_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSchedule",
			Handler:       _SchedularService_GetSchedule_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "SchedularService.proto",
}
